In [1]:
import pandas as pd
import numpy as np

In [3]:
read_csv_primary = pd.read_csv("../undata-country-profiles (1)/country_profile_variables.csv")
read_csv_ranking = pd.read_csv("../economy-rankings/Rankings.csv")

In [4]:
read_csv_ranking.rename(columns={'Economy':'country'}, inplace = True)

In [5]:
read_csv_ranking = read_csv_ranking.set_index('country')

In [6]:
read_csv_primary = read_csv_primary.set_index('country')

In [7]:
# Creating a list for the loc append.
list_countries_included = []
list_country_ids = []
list_countries_excluded = []

In [8]:
for i in range(len(read_csv_ranking)):
    
    for j in range(len(read_csv_primary)):

        if read_csv_primary.index[j] == read_csv_ranking.index[i]:
            list_countries_included.append(read_csv_ranking.index[i])#,read_csv_primary.loc['New Zealand',' country_id']})
            list_country_ids.append(read_csv_primary.iloc[j,0])

In [9]:
list_countries_included

['New Zealand',
 'Singapore',
 'Denmark',
 'United States Virgin Islands',
 'United Kingdom',
 'Norway',
 'Georgia',
 'Sweden',
 'Estonia',
 'Finland',
 'Australia',
 'Lithuania',
 'Ireland',
 'Canada',
 'Latvia',
 'Germany',
 'United Arab Emirates',
 'Austria',
 'Iceland',
 'Malaysia',
 'Mauritius',
 'Thailand',
 'Poland',
 'Spain',
 'Portugal',
 'France',
 'Netherlands',
 'Switzerland',
 'Japan',
 'Russian Federation',
 'Kazakhstan',
 'Slovenia',
 'Belarus',
 'Rwanda',
 'Montenegro',
 'Serbia',
 'Romania',
 'Italy',
 'Armenia',
 'Hungary',
 'Mexico',
 'Bulgaria',
 'Croatia',
 'Belgium',
 'Cyprus',
 'Israel',
 'Chile',
 'Brunei Darussalam',
 'Azerbaijan',
 'Peru',
 'Colombia',
 'Turkey',
 'Costa Rica',
 'Mongolia',
 'Luxembourg',
 'Puerto Rico',
 'Albania',
 'Bahrain',
 'Greece',
 'Morocco',
 'Jamaica',
 'Oman',
 'Indonesia',
 'El Salvador',
 'Uzbekistan',
 'Bhutan',
 'Ukraine',
 'China',
 'Panama',
 'Kenya',
 'Botswana',
 'South Africa',
 'Qatar',
 'Malta',
 'Zambia',
 'Bosnia and Herzegovina',
 'Samoa',
 'Tunisia',
 'Tonga',
 'Vanuatu',
 'Saudi Arabia',
 'San Marino',
 'Uruguay',
 'Seychelles',
 'Kuwait',
 'Guatemala',
 'Dominican Republic',
 'Dominican Republic',
 'India',
 'Fiji',
 'Trinidad and Tobago',
 'Jordan',
 'Lesotho',
 'Nepal',
 'Namibia',
 'Antigua and Barbuda',
 'Paraguay',
 'Papua New Guinea',
 'Malawi',
 'Sri Lanka',
 'Swaziland',
 'Philippines',
 'Honduras',
 'Solomon Islands',
 'Argentina',
 'Ecuador',
 'Ghana',
 'Belize',
 'Uganda',
 'Tajikistan',
 'Brazil',
 'Guyana',
 'Cabo Verde',
 'Palau',
 'Nicaragua',
 'Barbados',
 'Lebanon',
 'Cambodia',
 'Maldives',
 'Mozambique',
 'Senegal',
 'Grenada',
 'Mali',
 'Niger',
 'Nigeria',
 'Pakistan',
 'Burkina Faso',
 'Marshall Islands',
 'Mauritania',
 'Benin',
 'Bolivia (Plurinational State of)',
 'Guinea',
 'Djibouti',
 'Micronesia (Federated States of)',
 'Togo',
 'Kiribati',
 'Comoros',
 'Zimbabwe',
 'Sierra Leone',
 'Ethiopia',
 'Madagascar',
 'Cameroon',
 'Burundi',
 'Suriname',
 'Algeria',
 'Gabon',
 'Iraq',
 'Sudan',
 'Myanmar',
 'Liberia',
 'Equatorial Guinea',
 'Syrian Arab Republic',
 'Angola',
 'Guinea-Bissau',
 'Bangladesh',
 'Timor-Leste',
 'Chad',
 'Haiti',
 'Afghanistan',
 'Central African Republic',
 'Libya',
 'South Sudan',
 'Venezuela (Bolivarian Republic of)',
 'Eritrea',
 'Somalia']

In [10]:
for i in range(len(read_csv_ranking)):
    
        if read_csv_ranking.index[i] not in list_countries_included:
            
            list_countries_excluded.append(read_csv_ranking.index[i])

In [11]:
list_countries_excluded

['Korea, Rep.',
 'Hong Kong SAR, China',
 'Macedonia, FYR',
 'Taiwan, China',
 'Czech Republic',
 'Slovak Republic',
 'Kosovo',
 'Moldova',
 'Vietnam',
 'Kyrgyz Republic',
 'St. Lucia',
 'West Bank and Gaza',
 'Bahamas, The',
 'Iran, Islamic Rep.',
 'Egypt, Arab Rep.',
 'St. Vincent and the Grenadines',
 'St. Kitts and Nevis',
 'Tanzania',
 "Côte d'Ivoire",
 'Lao PDR',
 'Gambia, The',
 'São Tomé and Príncipe',
 'Congo, Rep.',
 'Congo, Dem. Rep.',
 'Yemen, Rep.']

In [12]:
list_countries_excludes_renamed = [
    "Democratic People's Republic of Korea",
    "China, Hong Kong SAR",
    "The former Yugoslav Republic of Macedonia",
    "Czechia",
    "Slovakia",
    "Republic of Moldova",
    "Viet Nam",
    "Kyrgyzstan",
    "Saint Lucia",
    "Bahamas",
    "Iran (Islamic Republic of)",
    "Egypt",
    "Saint Vincent and the Grenadines",
    "Saint Kitts and Nevis",
    "United Republic of Tanzania",
    "Lao People's Democratic Republic",
    "Gambia",
    "Sao Tome and Principe",
    "Congo",
    "Democratic Republic of the Congo",
    "Yemen"
]

In [ ]:
#Changing the index names on the ranking DF
read_csv_ranking = read_csv_ranking.rename( 
    index={
             'Korea, Rep.':"Democratic People's Republic of Korea",
             'Hong Kong SAR, China':"China, Hong Kong SAR",
             'Macedonia, FYR':"The former Yugoslav Republic of Macedonia",
             'Czech Republic':"Czechia",
             'Slovak Republic':"Slovakia",
             'Moldova':"Republic of Moldova",
             'Vietnam': "Viet Nam",
             'Kyrgyz Republic': "Kyrgyzstan",
             'St. Lucia': "Saint Lucia",
             'Bahamas, The':"Bahamas",
             'Iran, Islamic Rep.':"Iran (Islamic Republic of)",
             'Egypt, Arab Rep.':"Egypt",
             'St. Vincent and the Grenadines':"Saint Vincent and the Grenadines",
             'St. Kitts and Nevis':"Saint Kitts and Nevis",
             'Tanzania':"United Republic of Tanzania",
             'Lao PDR': "Lao People's Democratic Republic",
             'Gambia, The': "Gambia",
             'São Tomé and Príncipe': "Sao Tome and Principe",
             'Congo, Rep.': "Congo",
             'Congo, Dem. Rep.': "Democratic Republic of the Congo",
             'Yemen, Rep.': "Yemen"
        }
)

In [13]:
read_csv_ranking = read_csv_ranking.drop(['Taiwan, China','Kosovo','West Bank and Gaza',"Côte d'Ivoire"])

In [14]:
read_csv_primary.head()

,country_id,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,1,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
Albania,2,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
Algeria,3,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
American Samoa,4,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
Andorra,5,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99

In [17]:
for i in range(len(read_csv_ranking)):
    
    for j in range(len(read_csv_primary)):

        if read_csv_primary.index[j] == read_csv_ranking.index[i]:
            print(read_csv_primary.iloc[j,0])
            read_csv_ranking['country_id'][i] = read_csv_primary.iloc[j,0]

146
183
58
219
216
152
78
197
67
72
12
119
100
38
113
79
215
13
95
123
130
201
161
191
162
73
144
198
105
168
107
186
19
169
136
180
167
103
10
94
132
32
52
20
54
102
43
31
14
159
47
209
51
135
120
163
2
16
82
138
104
153
97
64
221
24
214
46
156
108
28
189
164
126
228
27
175
208
206
222
178
176
220
181
110
87
61
61
96
71
207
106
115
143
141
8
158
157
122
192
196
160
93
187
9
62
80
21
213
200
29
90
35
155
147
18
114
36
124
139
179
84
125
148
149
154
33
127
129
22
25
89
59
133
204
109
48
229
182
68
121
37
34
195
3
76
99
194
140
116
65
199
6
88
17
203
41
91
1
40
117
190
223
66
188

In [ ]:
read_csv_ranking.head(10)

In [18]:
read_csv_ranking.drop_duplicates()

,Ease of Doing Business Rank,Starting a Business,Dealing with Construction Permits,Getting Electricity,Registering Property,Getting Credit,Protecting Minority Investors,Paying Taxes,Trading across Borders,Enforcing Contracts,Resolving Insolvency,country_id
country,,,,,,,,,,,,
New Zealand,1,1,3,37,1,1,2,9,56,21,32,146
Singapore,2,6,16,12,19,29,4,7,42,2,27,183
Denmark,3,34,1,16,11,42,33,8,1,32,7,58
"Korea, Rep.",4,9,28,2,39,55,20,24,33,1,5,188
"Hong Kong SAR, China",5,3,5,4,55,29,9,3,31,28,43,188
United States Virgin Islands,6,49,36,49,37,2,42,36,36,16,3,219
United Kingdom,7,14,14,9,47,29,10,23,28,31,14,216
Norway,8,19,21,23,14,77,10,28,22,8,6,152
Georgia,9,4,29,30,4,12,2,22,62,7,57,78
Sweden,10,13,27,6,9,77,29,27,18,36,16,197
"Macedonia, FYR",11,22,26,53,48,12,4,29,27,35,30,188
Estonia,12,12,8,41,6,42,76,14,17,11,44,67
Finland,13,26,37,20,27,55,62,12,34,46,2,72
Australia,14,7,6,47,51,6,57,26,95,3,18,12
Lithuania,16,27,12,33,3,42,43,18,19,4,70,119
Ireland,17,8,30,35,40,42,10,4,47,98,17,100
Canada,18,2,54,105,33,12,8,16,46,114,11,38
Latvia,19,21,49,62,22,12,43,13,25,20,53,113
Germany,20,113,24,5,77,42,62,41,39,22,4,79
United Arab Emirates,21,51,2,1,10,90,10,1,91,12,69,215
Austria,22,118,42,22,31,77,29,39,1,9,23,13
Iceland,23,55,64,11,15,68,29,33,69,29,13,95
Malaysia,24,111,11,8,42,20,4,73,61,44,46,123
Mauritius,25,40,9,51,35,55,33,10,70,27,36,130
Thailand,26,36,43,13,68,42,16,67,57,34,26,201
Poland,27,120,41,54,38,29,51,51,1,55,22,161
Spain,28,86,123,42,53,68,24,34,1,26,19,191
Portugal,29,48,32,58,28,105,57,38,1,19,15,162
Czech Republic,30,81,127,15,32,42,62,53,1,91,25,188
France,31,25,18,26,100,90,33,54,1,15,28,73
...,...,...,...,...,...,...,...,...,...,...,...,...
Ethiopia,161,174,169,125,139,173,176,133,167,68,122,68
Madagascar,162,76,183,184,161,133,96,131,134,158,133,121
Cameroon,163,122,140,121,176,68,138,183,186,162,125,37
Burundi,164,42,168,182,95,177,132,138,164,150,144,34
Suriname,165,186,104,131,156,177,167,102,80,187,135,195
Algeria,166,145,146,120,163,177,170,157,181,103,71,3
Gabon,167,132,149,170,173,122,160,165,169,178,126,76
Iraq,168,154,93,116,101,186,124,129,179,144,168,99
São Tomé and Príncipe,169,148,103,115,171,159,187,135,114,185,168,188
Sudan,170,159,133,110,89,173,186,163,185,146,154,194
Myanmar,171,155,73,151,134,177,183,125,163,188,164,140
Liberia,172,54,184,176,183,105,177,69,177,174,106,116
Equatorial Guinea,173,182,160,146,162,122,146,177,174,104,168,65
Syrian Arab Republic,174,133,186,153,155,173,89,81,176,161,163,199
Angola,175,134,80,165,172,183,81,103,180,186,168,6
Guinea-Bissau,176,178,176,180,126,142,138,155,141,168,168,88
Bangladesh,177,131,130,185,185,159,76,152,173,189,152,17
Timor-Leste,178,151,159,114,187,170,81,139,98,190,168,203
"Congo, Rep.",179,177,125,181,177,133,146,185,184,155,118,188
Chad,180,185,153,177,159,142,160,188,172,154,150,41
Haiti,181,189,177,138,180,177,188,147,77,125,168,91
"Congo, Dem. Rep.",182,62,121,175,158,142,164,181,188,172,168,188
Afghanistan,183,107,185,163,186,105,189,176,175,181,161,1
Central African Republic,184,188,180,183,169,142,146,187,145,182,150,40
Libya,185,167,186,130,187,186,183,128,118,141,168,117
"Yemen, Rep.",186,163,186,187,82,186,132,80,189,140,156,188
South Sudan,187,181,178,187,181,177,177,66,178,81,168,190
Venezuela (Bolivarian Republic of),188,190,143,186,135,122,177,189,187,147,165,223
Eritrea,189,184,186,187,178,186,172,148,189,119,168,66
Somalia,190,187,186,187,150,186,190,190,160,110,168,188

# Exporting Dataframe to CSV

In [21]:
read_csv_ranking.to_csv(r'read_csv_ranking.csv')